// ============================================
// Common Types
// ============================================

export interface ApiResponse<T> {
  success: boolean;
  data: T;
  message: string;
  timestamp: string;
  traceId?: string;
}

export interface PagedResponse<T> {
  content: T[];
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
  last: boolean;
}

// ============================================
// Auth Types
// ============================================

export type Role = 'CUSTOMER' | 'OPERATIONS' | 'COMPLIANCE' | 'RECONCILIATION' | 'ADMIN';

export interface User {
  id: number;
  username: string;
  email: string;
  phone?: string;
  role: Role;
  active: boolean;
  /** True for staff users on first login until they rotate the temp password. */
  mustChangePassword?: boolean;
  /** True once the customer has set their transaction PIN (first-login mandatory). */
  pinSet?: boolean;
  partyId?: number;
  createdAt: string;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface RegisterRequest {
  name: string;
  username: string;
  email: string;
  password: string;
  phone: string;
  role?: Role;
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  expiresAt: string;
  user: User;
}

// ============================================
// Party Types
// ============================================

export type PartyType = 'INDIVIDUAL' | 'CORPORATE';
export type PartyStatus = 'ACTIVE' | 'INACTIVE' | 'SUSPENDED';

export interface Party {
  id: number;
  name: string;
  type: PartyType;
  phone?: string;
  country: string;
  riskRating: string;
  status: PartyStatus;
  createdAt: string;
  updatedAt: string;
}

export interface Account {
  id: number;
  partyId: number;
  partyName: string;
  accountNumber: string;
  ifscIban: string;
  alias?: string;
  currency: string;
  accountType: string;
  vpaUpiId?: string;
  phone?: string;
  email?: string;
  active: boolean;
  createdAt: string;
}

export type AliasType = 'VPA' | 'PHONE' | 'EMAIL' | 'NAME';

export interface AccountValidationResponse {
  exists: boolean;
  active: boolean;
  currency: string;
  partyName: string;
  accountId: number;
  partyId: number;
}

// ============================================
// Payment Types
// ============================================

export type PaymentStatus =
  | 'INITIATED' | 'VALIDATED' | 'VALIDATION_FAILED'
  | 'SCREENING' | 'HELD' | 'ROUTED'
  | 'PROCESSING' | 'COMPLETED' | 'FAILED' | 'CANCELLED' | 'REVERSED';

export type InitiationChannel = 'BRANCH' | 'MOBILE' | 'ONLINE' | 'API';

export interface PaymentOrder {
  id: number;
  /** Customer-facing opaque reference (e.g. PRX9K3M7F2A8) — generated by payment-service. */
  reference?: string;
  idempotencyKey?: string;
  debtorAccountId: number;
  creditorAccountId: number;
  amount: number;
  currency: string;
  purposeCode?: string;
  initiationChannel: InitiationChannel;
  status: PaymentStatus;
  initiatedBy?: number;
  createdAt: string;
  updatedAt: string;
  validationResults?: ValidationResult[];
}

export interface ValidationResult {
  id: number;
  paymentId: number;
  ruleName: string;
  result: 'PASS' | 'FAIL';
  message?: string;
  checkedAt: string;
}

export type PaymentMethod = 'UPI' | 'BANK_TRANSFER' | 'OTHER';

export interface PaymentInitiationRequest {
  debtorAccountId: number;
  creditorAccountId: number;
  amount: number;
  currency: string;
  purposeCode?: string;
  initiationChannel?: InitiationChannel;
  paymentMethod?: PaymentMethod;
  /** 4–6 digit transaction PIN. Required for customer-initiated payments. */
  transactionPin?: string;
  idempotencyKey?: string;
}

// ============================================
// Routing Types
// ============================================

export type RailType = 'BOOK' | 'NEFT' | 'RTGS' | 'IMPS' | 'ACH' | 'WIRE';
export type RailStatus = 'PENDING' | 'SENT' | 'ACKNOWLEDGED' | 'SETTLED' | 'REJECTED' | 'FAILED';

export interface RoutingRule {
  id: number;
  name: string;
  description?: string;
  conditionJson: string;
  preferredRail: RailType;
  priority: number;
  active: boolean;
  createdAt: string;
}

export interface RailInstruction {
  id: number;
  paymentId: number;
  rail: RailType;
  correlationRef: string;
  railStatus: RailStatus;
  retryCount: number;
  maxRetries: number;
  sentAt?: string;
  completedAt?: string;
  failureReason?: string;
  createdAt: string;
}

// ============================================
// Ledger Types
// ============================================

export type EntryType = 'DEBIT' | 'CREDIT' | 'FEE' | 'TAX' | 'REVERSAL';
export type FeeType = 'FLAT' | 'PERCENTAGE';

export interface LedgerEntry {
  id: number;
  paymentId: number;
  accountId: number;
  entryType: EntryType;
  amount: number;
  currency: string;
  narrative?: string;
  balanceAfter?: number;
  entryDate: string;
}

export interface FeeSchedule {
  id: number;
  product: string;
  rail: RailType;
  feeType: FeeType;
  value: number;
  minFee: number;
  maxFee?: number;
  currency: string;
  effectiveFrom: string;
  effectiveTo?: string;
  active: boolean;
}

export interface AccountSummary {
  accountId: number;
  totalDebits: number;
  totalCredits: number;
  totalFees: number;
  netBalance: number;
  currency: string;
  entryCount: number;
}

// ============================================
// Compliance Types
// ============================================

export type CheckType = 'SANCTIONS' | 'AML' | 'PEP' | 'GEO';
export type CheckResult = 'CLEAR' | 'FLAG' | 'HOLD';
export type HoldStatus = 'ACTIVE' | 'RELEASED' | 'ESCALATED' | 'REJECTED';

export interface ComplianceCheck {
  id: number;
  paymentId: number;
  checkType: CheckType;
  severity: string;
  result: CheckResult;
  details?: Record<string, unknown>;
  checkedBy: string;
  checkedAt: string;
}

export interface Hold {
  id: number;
  paymentId: number;
  reason: string;
  placedBy: number;
  status: HoldStatus;
  releaseNotes?: string;
  releasedBy?: number;
  placedAt: string;
  releasedAt?: string;
}

// ============================================
// Exception Types
// ============================================

export type ExceptionCategory = 'VALIDATION' | 'RAIL' | 'POSTING' | 'COMPLIANCE' | 'SYSTEM';
export type ExceptionStatus = 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'ESCALATED' | 'CLOSED';
export type ReturnStatus = 'NOTIFIED' | 'PROCESSING' | 'POSTED' | 'CLOSED';
export type ReconResult = 'MATCHED' | 'UNMATCHED' | 'PARTIAL' | 'DISCREPANCY';

export interface ExceptionCase {
  id: number;
  paymentId: number;
  category: ExceptionCategory;
  description: string;
  ownerId?: number;
  status: ExceptionStatus;
  resolution?: string;
  priority: string;
  createdAt: string;
  resolvedAt?: string;
}

export interface ReturnItem {
  id: number;
  paymentId: number;
  reasonCode: string;
  reasonDesc?: string;
  amount: number;
  currency: string;
  status: ReturnStatus;
  returnDate: string;
  processedAt?: string;
}

export interface ReconciliationRecord {
  id: number;
  source: 'RAIL' | 'LEDGER';
  referenceId: number;
  counterpartId?: number;
  reconDate: string;
  result: ReconResult;
  amount?: number;
  currency?: string;
  notes?: string;
  resolved: boolean;
}

// ============================================
// Settlement Types
// ============================================

export type BatchStatus = 'PENDING' | 'PROCESSING' | 'POSTED' | 'RECONCILED' | 'FAILED';
export type ReportScope = 'PRODUCT' | 'RAIL' | 'PERIOD' | 'DAILY' | 'MONTHLY' | 'CUSTOM';

export interface SettlementBatch {
  id: number;
  rail: RailType;
  periodStart: string;
  periodEnd: string;
  totalCount: number;
  totalAmount: number;
  netAmount?: number;
  totalFees?: number;
  currency: string;
  status: BatchStatus;
  postedDate?: string;
  createdAt: string;
}

export interface PaymentReport {
  id: number;
  reportName: string;
  scope: ReportScope;
  parameters?: Record<string, unknown>;
  metrics: Record<string, unknown>;
  status: 'GENERATING' | 'COMPLETED' | 'FAILED';
  generatedAt?: string;
  createdAt: string;
}

// ============================================
// Notification Types
// ============================================

export type NotificationCategory = 'PAYMENT' | 'COMPLIANCE' | 'EXCEPTION' | 'SETTLEMENT' | 'SYSTEM';

export interface Notification {
  id: number;
  userId: number;
  title: string;
  message?: string;
  category: NotificationCategory;
  severity: 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL';
  referenceType?: string;
  referenceId?: number;
  isRead: boolean;
  createdAt: string;
  readAt?: string;
}

// ============================================
// Audit Types
// ============================================

export interface AuditLog {
  id: number;
  userId: number;
  username?: string;
  action: string;
  entityType?: string;
  entityId?: number;
  details?: string;
  ipAddress?: string;
  createdAt: string;
}
